// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xeigwisfczwtlmctpcwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlaWd3aXNmY3p3dGxtY3RwY3dhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NzIyNDksImV4cCI6MjA2NDU0ODI0OX0.1zoJ0pXsjohPterhELiWuW8hFZKY-V-UMd0MmQDQ6qM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);